security:
    password_hashers:
       App\Entity\User:
            algorithm: auto
        # Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\CustomAuthenticator
            stateless: false
            logout:
                path: app_logout
                target: /login


        
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/user/profile/edit, roles: ['ROLE_ADMIN','ROLE_STAFF','ROLE_USER'] }
        - { path: ^/user/customer, roles: ['ROLE_ADMIN','ROLE_STAFF'] }
        - { path: ^/user/profile, roles: ['ROLE_ADMIN','ROLE_STAFF'] }
        - { path: ^/booking, roles: ['ROLE_ADMIN','ROLE_STAFF'] }
        - { path: ^/booking/new, roles: ['ROLE_ADMIN','ROLE_STAFF'] }
        - { path: ^/room, roles: ['ROLE_ADMIN','ROLE_STAFF'] }
        - { path: ^/room/new, roles: ['ROLE_ADMIN'] }
        - { path: ^/room/edit, roles: ['ROLE_ADMIN'] }
        - { path: ^/room/delete, roles: ['ROLE_ADMIN'] }
        - { path: ^/user/new, roles: ['ROLE_ADMIN'] }
        - { path: ^/user/edit, roles: ['ROLE_ADMIN'] }
        - { path: ^/user/show, roles: ['ROLE_ADMIN'] }
        - { path: ^/user/delete, roles: ['ROLE_ADMIN'] }
        - { path: ^/history, roles: ['ROLE_ADMIN'] }
        - { path: ^/user$, roles: ['ROLE_ADMIN'] }
      
       
        

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
             

